# Only store settings here tht must be in config.yml,
# otherwise put them in _data/settings.yml.

# Set baseurl mainly for GitHub Pages URL
baseurl: /jekyll-starter

# Set pretty permalinks, not Jekyll default 'date'
permalink: pretty

# Jekyll shouldn't process these files
exclude: [
README.md,
Gemfile,
Gemfile.lock,
package.json,
package-lock.json,
node_modules,
gulpfile.js,
eslint.json,
# images
]

keep_files: [
# images
]

# Set default page layout for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      excerpt: ""
